In [1]:
lst = []
lst.append('Hello')
print(lst)

['Hello']


In [2]:
lst.insert(1,'World')
print(lst)

['Hello', 'World']


In [3]:
lst = [10,20,30,40,50]
lst.append(60)
print(lst)
lst.insert(2,400)
print(lst)


[10, 20, 30, 40, 50, 60]
[10, 20, 400, 30, 40, 50, 60]


In [4]:
lst = lst = [10,20,[30,40,[50,60,[70,[80,[[40]]]]],70],80]

print(lst)

[10, 20, [30, 40, [50, 60, [70, [80, [[40]]]]], 70], 80]


In [5]:
print(lst[2][2][2][1][1][0][0])

40


In [6]:
lst = [10,20,(100,200),[300,400,900]]
print(lst[2][1])

200


In [7]:
tup = (100,200,300,400,[600,700])
print(tup)

(100, 200, 300, 400, [600, 700])


In [8]:
dict = {
    'A':10,
    'B':20,
    'C':30
}

print(dict)

{'A': 10, 'B': 20, 'C': 30}


In [9]:
dict.update({'D':80})
dict

{'A': 10, 'B': 20, 'C': 30, 'D': 80}

In [10]:
dict = {'India':[100,300,500],
        'USA':[500,600,700,800],
        'UK':['HI','World','Python']}
dict

{'India': [100, 300, 500],
 'USA': [500, 600, 700, 800],
 'UK': ['HI', 'World', 'Python']}

In [11]:
dict['UK'][2]

'Python'

In [12]:
for i in range(0,10):
    print(i)


0
1
2
3
4
5
6
7
8
9


In [13]:
for i in range(0,10):
    print(i)
    if i == 5:
        break


0
1
2
3
4
5


In [14]:
for i in range(0,10):
    if i % 2 == 0:
        print(i)

0
2
4
6
8


In [15]:
dict = {
    'India':[1000,2000,3000],
    'USA':(100,200,300),
    'Uk':{'India','PAK','UAE'}
}
dict

{'India': [1000, 2000, 3000],
 'USA': (100, 200, 300),
 'Uk': {'India', 'PAK', 'UAE'}}

In [16]:
for i in range(0,10):
    if i == 5:
        continue 
    print(i)

0
1
2
3
4
6
7
8
9


In [17]:
if 1 == 1:
    print("hello world")

hello world


In [18]:
num = float(input("Enter the number : "))

threshold = 200

if num > threshold:
    print("The Num value is greate")
    
else:
    print("The Threshould value is bigger ")

The Threshould value is bigger 


In [19]:
marks = float(input("Enter the marks : "))

if marks > 80:
    print("Bright Student")
elif marks > 70 and marks < 79:
    print("Good Student")
elif marks > 60 and marks < 69:
    print("Average Student")
elif marks > 50 and marks < 59:
    print("Weak Student")
else:
    print("Low Grade") 




Low Grade


In [20]:
withdraw = int(input("Enter the amount"))
balance = 5000

if withdraw <= balance:
    balance -= withdraw
    print(f'Withdrawl succesful! Current Amount is {balance}' )
else:
    print("insuffecient balance")

Withdrawl succesful! Current Amount is 4996


In [21]:
for i in range(1,10):
    print('*' * i)

*
**
***
****
*****
******
*******
********
*********


In [22]:
for i in range(5,0,-1):
    print('*' * i)

*****
****
***
**
*


In [23]:
for i in range(0,10):
    print('*' * i)

for j in range(10,0,-1):
    print('&' * j)


*
**
***
****
*****
******
*******
********
*********
&&&&&&&&&&
&&&&&&&&&
&&&&&&&&
&&&&&&&
&&&&&&
&&&&&
&&&&
&&&
&&
&


In [24]:
#lamda function
add = lambda x,y: x+y
print(add(100,200))

300


In [25]:
mul = lambda x,y: x*y

In [26]:
num1= float(input("enter a number1"))
num2= float(input("enter a  number2"))

num = mul(num1,num2)
print(num)

20.0


In [27]:
class abc:
    print('hii')

obj = abc()

hii


In [28]:
class my_car:
    pass

In [29]:
class meet:
    
    i = 12345 #Attribute

    def f(self): #Method
        return "Hello World"
    
x = meet()

print(x.i)
 
print(x.f())

12345
Hello World


In [30]:
def __init__(self):
    self.data = []

In [31]:
# class abc:
#     def __init__(self):
#         self.num1 = 1000
#         self.num2 = 2000
        

# m = abc()

# m.num1

class abc:
    def __init__(self):
        self.num1 = 1000  # You can ignore the parameters if you're hardcoding values
        self.num2 = 2000
    
    def showdata(self):
        print(f'{self.num1}')
        print(f'{self.num2}')

# Create an object with two arguments (even though they’re not used)
x = abc()

# Call the method
x.showdata()

1000
2000


In [32]:
class my_car:
    def __init__(self,brand,model,colour,fuel_type):
        self.brand = brand
        self.model = model
        self.colour = colour
        self.fuel_type = fuel_type

    def show_car(self):
            print(f'''The Car Brand is {self.brand}
                The Car Model is {self.model}
                The Car Colour is {self.colour}
                The Car Fuel_Type is {self.fuel_type}''')
            
car1 = my_car('Porsche','911','Red','Petrol')
print(car1.show_car())
car2 = my_car('BMW','X7','Black','Petrol')
print(car2.show_car())
car3 = my_car('Hyundai','Alcazar','Red','Diesel')
print(car3.show_car())
car4 = my_car('Porsche','Panamera','Brown','Petrol')
print(car4.show_car())
car5 = my_car('Mercedes','C-Class','Black','Petrol')
print(car5.show_car())




The Car Brand is Porsche
                The Car Model is 911
                The Car Colour is Red
                The Car Fuel_Type is Petrol
None
The Car Brand is BMW
                The Car Model is X7
                The Car Colour is Black
                The Car Fuel_Type is Petrol
None
The Car Brand is Hyundai
                The Car Model is Alcazar
                The Car Colour is Red
                The Car Fuel_Type is Diesel
None
The Car Brand is Porsche
                The Car Model is Panamera
                The Car Colour is Brown
                The Car Fuel_Type is Petrol
None
The Car Brand is Mercedes
                The Car Model is C-Class
                The Car Colour is Black
                The Car Fuel_Type is Petrol
None


In [ ]:
import logging
logging.basicConfig(level=logging.INFO,
                    filemode='w',
                    format='%(asctime)s - %(levelname)s - %(message)s',
                    filename = 'model.log',force = True)



class Banking:
    def __init__(self):
        self.balance = 10000
        self.withdraw = float(input("Enter the Amount: "))

    def bal(self):
        if self.balance <= self.withdraw:
            print("Withdraw Amount is Higher")
        else:
            self.balance -= self.withdraw

    def show_balance(self):
        print(f"The Current Balance is {self.balance}")

# Create object and perform actions 
wtdr = Banking()
wtdr.bal()
wtdr.show_balance()

logging.info('Log Created')

The Current Balance is 9995.0


In [34]:
import numpy as np

np.__version__

lst = [10,20,30]

print(type(lst))

<class 'list'>


In [35]:
arr = np.array(lst)
print(type(arr))

<class 'numpy.ndarray'>


In [36]:
lst1 = [[10,20,30,40]]

In [37]:
arr1 = np.array(lst1)
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[[10 20 30 40]]


In [38]:
arr1.shape

(1, 4)

In [39]:
darray = [[[[[10,20,40],[30,50,60],[60,40,60]]]]]

arr = np.array(darray)
print(arr.shape)

(1, 1, 1, 3, 3)


In [40]:
lst = [13,4,5]
arr = np.array(lst)

print(arr.ndim)

1


In [41]:
lst = [[[[[13,4,5],[4,5,6]]]]]
arr = np.array(lst)

print(arr.ndim)

5


In [42]:
tup = (3,4)

np.zeros(tup)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
import numpy as np

matrix = np.random.rand(3, 3)  # 3 rows, 4 columns
print(matrix)

[[0.27159943 0.50934016 0.27097298]
 [0.44415302 0.40337274 0.9646353 ]
 [0.73134528 0.06241296 0.62735767]]


In [44]:
import pandas as pd

a = pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [45]:
c = pd.DataFrame({'IND': [100,200,300],'PAK':[100,200,300],'UAE':[100,200,300]})

print(c)

   IND  PAK  UAE
0  100  100  100
1  200  200  200
2  300  300  300


In [46]:
print(c['IND'][2])

300
