In [2]:
import numpy as np
print(np.__version__)

2.1.3


In [3]:
#Arrays

a = np.array([1,2,3])
b = np.array([[1,2,3],
              [4,5,6]])

print('1D:',a)
print('2D:',b)

1D: [1 2 3]
2D: [[1 2 3]
 [4 5 6]]


In [4]:
print('Shape:',b.shape)    
print('Size:',b.size)
print('Dtpye:',b.dtype)

Shape: (2, 3)
Size: 6
Dtpye: int64


In [5]:
zeros = np.zeros((3,3))
ones = np.ones((3,3))
full = np.full((3,3),10)
eye = np.eye(3)
randint = np.random.rand(3,3)

print(zeros,ones,full,eye,randint,sep='\n\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0.65549705 0.58666661 0.84036274]
 [0.45193019 0.03752848 0.5949182 ]
 [0.01087384 0.88091973 0.6657173 ]]


In [6]:
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [7]:
lin = np.linspace(0,1,5)
lin

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
#Array Indexing and Slicing
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr)
print('Value:',arr[0,2])
print('Value:',arr[1,2])
print('Value:',arr[2,2])

print(arr[0])
print(arr[1])
print(arr[2])

print('Accessing the Column: ',arr[:,1]) #Accessing the Column
print('Accesing the Subarray: \n',arr[1:,1:]) #Accessing the subarray

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Value: 3
Value: 6
Value: 9
[1 2 3]
[4 5 6]
[7 8 9]
Accessing the Column:  [2 5 8]
Accesing the Subarray: 
 [[5 6]
 [8 9]]


In [9]:
#Array Manipulation
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a.reshape(9,)
c = a.flatten()
d = np.transpose(a)

print('Reshaped:',b)
print('Flattened:',c)
print('Transposed:',d)

Reshaped: [1 2 3 4 5 6 7 8 9]
Flattened: [1 2 3 4 5 6 7 8 9]
Transposed: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
#Mathematical Operations
a = np.array([1,2,3])
b = np.array([4,5,6])

print('Add:',a+b)
print('Multiply:',a*b)
print('Dot:',np.dot(a,b))
print('Mean:',np.mean(a))
print('Std Dev:',np.std(a))
print('Sum Axis 0:',np.sum([a,b],axis=0))
print('Sum Axis 1:',np.sum([a,b],axis=1))

Add: [5 7 9]
Multiply: [ 4 10 18]
Dot: 32
Mean: 2.0
Std Dev: 0.816496580927726
Sum Axis 0: [5 7 9]
Sum Axis 1: [ 6 15]


In [11]:
#Boolean Indexing and Masking
arr = np.array([1,2,3,4,5])
mask = arr >= 3

print('Mask:',mask)
print('Filtered:',arr[mask])

Mask: [False False  True  True  True]
Filtered: [3 4 5]


In [12]:
#BroadCasting

a = np.array([1,2,3])
b = np.array(([1],[2],[3]))

print(a + b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [13]:
a = np.array([1,2,3])
b = a.view()
c = a.copy()

a[0] = 99
print('Original:',a)
print('View:',b)
print('Copy:',c)

Original: [99  2  3]
View: [99  2  3]
Copy: [1 2 3]


In [30]:
a = np.array([[1,2,3],
              [3,4,4]])
print('Max:',np.max(a))
print('ArgMax:',np.argmax(a)) #Flattened the array and return the index of the max value
print('Clip:',np.clip(a,1,2))
print('Unique:',np.unique(a))

Max: 4
ArgMax: 4
Clip: [[1 2 2]
 [2 2 2]]
Unique: [1 2 3 4]


In [33]:
data = np.array([[1,2,3,4,5]])

print('Mean',np.mean(data))
print('Median:',np.median(data))

Mean 3.0
Median: 3.0


In [ ]:
#Sorting and Searching
a = np.array([3,2,1,5,6,4])

sorting_indices = np.argsort(a)
print('Sorted:',np.sort(a))
print('Indices:',np.argsort(a))


for i in sorting_indices:
    print(f'Value: {i} at Index: {a[i]}')

Sorted: [1 2 3 4 5 6]
Indices: [2 1 0 5 3 4]
Value: 2 at Index: 1
Value: 1 at Index: 2
Value: 0 at Index: 3
Value: 5 at Index: 4
Value: 3 at Index: 5
Value: 4 at Index: 6


In [77]:
arr = np.array([20,30,40,45,70,100])
print('Search Sorted:',np.searchsorted(arr, 44)) #We want to enter the value 44 the searchsorted returns the index where he'll enter the value

Search Sorted: 3


In [79]:
a = np.array([1,2])
b = np.array([3,4])

print('HStack:',np.hstack((a,b)))
print('VStack:',np.vstack((a,b)))

HStack: [1 2 3 4]
VStack: [[1 2]
 [3 4]]


In [ ]:
arr = np.array([[1,2],[3,4]])
print('Split:',np.split(arr,2)) #Splits the arrays

Split: [array([[1, 2]]), array([[3, 4]])]


In [88]:
#Random Function
np.random.seed(0)
print('Randint:\n',np.random.randint(1,10,(3,3)))
print('Randn:\n',np.random.randn(3))

Randint:
 [[6 1 4]
 [4 8 4]
 [6 3 5]]
Randn:
 [-0.29139398 -0.13309028 -0.1730696 ]
